import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0e0e0e',
        surface: '#0e0e0e',
        'surface-container-low': '#131313',
        'surface-container': '#1a1a1a',
        'surface-container-high': '#20201f',
        'surface-container-highest': '#262626',
        'surface-variant': '#262626',
        'surface-bright': '#2c2c2c',
        'surface-dim': '#0e0e0e',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        'on-background': '#ffffff',
        primary: '#ffa44c',
        'primary-fixed': '#fd9000',
        'primary-fixed-dim': '#ea8400',
        'primary-dim': '#ea8400',
        'primary-container': '#fd9000',
        'on-primary': '#552d00',
        'on-primary-fixed': '#1e0c00',
        'on-primary-container': '#462400',
        'on-primary-fixed-variant': '#532b00',
        'surface-tint': '#ffa44c',
        'inverse-primary': '#8f4f00',
        secondary: '#feb64c',
        'secondary-fixed': '#ffc87f',
        'secondary-fixed-dim': '#feb64c',
        'secondary-dim': '#eea840',
        'secondary-container': '#835500',
        'on-secondary': '#583700',
        'on-secondary-fixed': '#4a2e00',
        'on-secondary-fixed-variant': '#704800',
        'on-secondary-container': '#fff6ef',
        tertiary: '#ffded5',
        'tertiary-fixed': '#ffccbc',
        'tertiary-fixed-dim': '#f0beae',
        'tertiary-dim': '#f0beae',
        'tertiary-container': '#ffccbc',
        'on-tertiary': '#6f4b3f',
        'on-tertiary-fixed': '#503025',
        'on-tertiary-fixed-variant': '#704b3f',
        'on-tertiary-container': '#664237',
        outline: '#767575',
        'outline-variant': '#484847',
        error: '#ff7351',
        'error-dim': '#d53d18',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-error-container': '#ffd2c8',
        'inverse-surface': '#fcf9f8',
        'inverse-on-surface': '#565555',
        'surface-container-lowest': '#000000',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        float: '0px 24px 48px rgba(0,0,0,0.5)',
      },
    },
  },
  plugins: [],
}

export default config
